//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace satis.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("satis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _543_5435420_popcorn_png_image_popcorn_cinema_logo_png_transparent {
            get {
                object obj = ResourceManager.GetObject("543-5435420_popcorn-png-image-popcorn-cinema-logo-png-transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap anasayfa_toptancay_satis_sitesi {
            get {
                object obj = ResourceManager.GetObject("anasayfa_toptancay_satis_sitesi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap guncel_bardak {
            get {
                object obj = ResourceManager.GetObject("guncel bardak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_logo_food_popcorn_others_miscellaneous_baking {
            get {
                object obj = ResourceManager.GetObject("png-clipart-logo-food-popcorn-others-miscellaneous-baking", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_logo_food_popcorn_others_miscellaneous_baking1 {
            get {
                object obj = ResourceManager.GetObject("png-clipart-logo-food-popcorn-others-miscellaneous-baking1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_popcorn_ticket_and_gold_ribbon_illustration_film_poster_cinema_clapperboard_popcorn_poster_happy_birthday_vector_images {
            get {
                object obj = ResourceManager.GetObject("png-clipart-popcorn-ticket-and-gold-ribbon-illustration-film-poster-cinema-clappe" +
                        "rboard-popcorn-poster-happy-birthday-vector-images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_popcorn_ticket_and_gold_ribbon_illustration_film_poster_cinema_clapperboard_popcorn_poster_happy_birthday_vector_images1 {
            get {
                object obj = ResourceManager.GetObject("png-clipart-popcorn-ticket-and-gold-ribbon-illustration-film-poster-cinema-clappe" +
                        "rboard-popcorn-poster-happy-birthday-vector-images1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_raffle_ticket_graphy_drawing_casino_raffle_ticket_fundraising_tiket {
            get {
                object obj = ResourceManager.GetObject("png-clipart-raffle-ticket-graphy-drawing-casino-raffle-ticket-fundraising-tiket", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_raffle_ticket_graphy_drawing_casino_raffle_ticket_fundraising_tiket1 {
            get {
                object obj = ResourceManager.GetObject("png-clipart-raffle-ticket-graphy-drawing-casino-raffle-ticket-fundraising-tiket1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_ticket_ticket_miscellaneous_template_brand_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-transparent-ticket-ticket-miscellaneous-template-brand-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_two_gold_tickets_ilustration_raffle_ticket_prize_gold_thanksgiving_raffle_ticket_brand_house_thanksgiving_raffle_ticket {
            get {
                object obj = ResourceManager.GetObject("png-transparent-two-gold-tickets-ilustration-raffle-ticket-prize-gold-thanksgivin" +
                        "g-raffle-ticket-brand-house-thanksgiving-raffle-ticket", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap susisesi_1024x1024 {
            get {
                object obj = ResourceManager.GetObject("susisesi-1024x1024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
